const techRoles = [
    "Software Developer",
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "AI Specialist",
    "Database Administrator",
    "System Administrator",
    "Network Engineer",
    "Cybersecurity Specialist",
    "Blockchain Developer",
    "Game Developer",
    "Smart Contract Developer",
    "UI/UX Designer",
    "Product Manager",
    "Project Manager",
    "Quality Assurance Engineer",
    "Technical Support Specialist",
    "IT Consultant",
    "Systems Architect",
    "Software Engineer in Test",
    "Site Reliability Engineer",
    "IT Manager",
    "Business Analyst",
    "IT Auditor",
    "Technical Writer",
    "Security Analyst",
    "Network Administrator",
    "Embedded Systems Engineer",
    "IoT Developer",
    "Big Data Engineer",
    "Robotics Engineer",
    "IT Support Specialist"
];

export default techRoles;