const techstacks = [
    'HTML/CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'React Native',
    'React.js',
    'Angular',
    'Vue.js',
    'Node.js',
    'Next.js',
    'Express.js',
    'Python',
    'Django',
    'Flask',
    'Java',
    'Spring Boot',
    'Ruby',
    'Ruby on Rails',
    'Rust',
    'PHP',
    'Laravel',
    'ASP.NET',
    'C',
    'C#',
    'C++',
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'SQLite',
    'Redis',
    'GraphQL',
    'REST API',
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'Docker',
    'Kubernetes',
    'Git',
    'Jenkins',
    'CircleCI',
    'CI/CD',
    'Agile Methodologies',
    'Scrum',
    'Kanban',
    'Machine Learning',
    'Data Science',
    'TensorFlow',
    'PyTorch',
    'NLP (Natural Language Processing)',
    'Computer Vision',
    'Blockchain',
    'Solidity',
    'Ethereum',
    'Web3.js',
];

export default techstacks;
